# Generated by Django 2.1.1 on 2018-09-26 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('mobile', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Mobile number must be entered in the format: '+999999999', 10 digits allowed.", regex='^(+\\d{1,3})?,?\\s?\\d{8,13}')])),
                ('address', models.TextField(max_length=200)),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=6)),
                ('blood_group', models.CharField(choices=[('Aplus', 'A+'), ('Aminus', 'A-'), ('Bplus', 'B+'), ('Bminus', 'B-'), ('Oplus', 'O+'), ('Ominus', 'O-'), ('ABplus', 'AB+'), ('ABminus', 'AB-')], default='Aplus', max_length=128)),
            ],
        ),
    ]
